# Generated by Django 3.0.6 on 2020-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_delete_chat_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to='room_pics')),
            ],
        ),
    ]
