# Generated by Django 3.0.6 on 2020-07-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chat_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_room',
        ),
    ]
