# Generated by Django 3.0.6 on 2020-07-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.Chat_room'),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.Chat_room'),
        ),
    ]
