# Generated by Django 3.0.6 on 2020-07-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='portfolio')),
                ('img2', models.ImageField(upload_to='portfolio')),
                ('img3', models.ImageField(upload_to='portfolio')),
                ('img4', models.ImageField(upload_to='portfolio')),
                ('img5', models.ImageField(upload_to='portfolio')),
                ('img6', models.ImageField(upload_to='portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
