# Generated by Django 3.0.6 on 2020-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200725_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='img1',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
